// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyvyWHHLkX2ArLIc1CgRIWzHTCc2hexBY',
    appId: '1:574451792770:web:9418eb92f97fab9b0aed9b',
    messagingSenderId: '574451792770',
    projectId: 'thinkninja-c11a3',
    authDomain: 'thinkninja-c11a3.firebaseapp.com',
    storageBucket: 'thinkninja-c11a3.appspot.com',
    measurementId: 'G-HQ9HBQZWY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClbF-13X5c4z9LPengeuCjSE0YPZGg7bw',
    appId: '1:574451792770:android:3dcf6c5fcbfddc3f0aed9b',
    messagingSenderId: '574451792770',
    projectId: 'thinkninja-c11a3',
    storageBucket: 'thinkninja-c11a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2-TxJBRxhmUEC1imZluTZd5_YXjy8j6M',
    appId: '1:574451792770:ios:bac8920527a8aa0f0aed9b',
    messagingSenderId: '574451792770',
    projectId: 'thinkninja-c11a3',
    storageBucket: 'thinkninja-c11a3.appspot.com',
    iosBundleId: 'com.example.thinkninja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2-TxJBRxhmUEC1imZluTZd5_YXjy8j6M',
    appId: '1:574451792770:ios:bac8920527a8aa0f0aed9b',
    messagingSenderId: '574451792770',
    projectId: 'thinkninja-c11a3',
    storageBucket: 'thinkninja-c11a3.appspot.com',
    iosBundleId: 'com.example.thinkninja',
  );
}
